site_name: Ralistic Datasets Fabric

theme:
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.annotate    

  name: material
  custom_dir: material

  logo: assets/images/logaritex.998.svg
  favicon: assets/images/logaritex.998.svg
  
  palette:
  #   primary: blue grey
  #   accent: cyan
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
#        primary: blue grey
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_url: https://github.com/logaritex

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Page tree
nav:
  - Home: index.md
  - Data Generator:
    - Quick start: data-generator-getting-started.md
    - Usage: data-generator-usage.md
#    - Javadoc: 
  - Stream Data Generator:
    - Quick start: stream-data-generator-getting-started.md
    # - Contributing: contributing.md
    # - License: license.md
#    - Changelog:
#      - Changes: changelog/index.md
#      - How to upgrade: upgrade.md
#   - Releases:

copyright: "Copyright © 2022 The Data Generator Authors"

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/christzolov
    - icon: fontawesome/brands/github
      link: https://github.com/logaritex
      name: Dataset Fabric Community on Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tzolov/
      name: LinkedIn