site_name: Ralistic Data Generator

theme:
  features:
    - navigation.tabs
  name: material
  logo: assets/icon-tanzu.svg
  favicon: assets/icon-tanzu.svg
  palette:
    primary: blue grey
    accent: cyan

repo_url: https://github.com/logaritex/data-generator


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
